#%RAML 1.0 NamedExample
  {
      
      orderName: "apple",
      orderid: 456236,
      orderType: "premium",
      "amount": 587,
      "created": 1589068800002,
      "discountid": 200,
      "modified": 1589068800005,
      "status": "ok",
      "userid": 1000,
      "addressid": 2589068800001,


   }

  
  