#%RAML 1.0 NamedExample
   
  [     
          
  {
      
      username: "samuelabebaw94",
      email: "taju8@example.com",
      userid: 965,
      password: 352
                
      
  },
  {
      
      username: "samuelabebaw94",
      email: "taju8@example.com",
      userid: 965,
      password: 352
                
      
  }
  ]
  
           
    