#%RAML 1.0 Overlay
extends: online-shopping-group-c.raml
title: online shopping overview
documentation:
  - title: ovdrview
    content: the document define about the online shopping
    /product:
usage: to provide additional information about the API