#%RAML 1.0 NamedExample
[
{"orderid":1510,
"userid":1812,
"addressid":201,
"discountid":1,
"created":1603218644000,
"modified":"null",
"status":"Shipment Completed",
"amount":1000.0},

{"orderid":1510,
"userid":1813,
"addressid":201,
"discountid":1,
"created":1603218787000,
"modified":"null",
"status":"Shipment Completed",
"amount":1000.0},

{"orderid":1512,
"userid":1814,
"addressid":201,
"discountid":1,
"created":1603220052000,
"modified":"null",
"status":"Shipment Completed",
"amount":1000.0},

{"orderid":1513,
"userid":11815,
"addressid":201,
"discountid":1,
"created":1603220259000,
"modified":"null",
"status":"Shipment Completed",
"amount":1000.0},

{"orderid":1514,
"userid":1816,
"addressid":201,
"discountid":1,
"created":1603236517000,
"modified":"null",
"status":"Shipment Completed",
"amount":1000.0},

{"orderid":1515,
"userid":1817,
"addressid":201,
"discountid":1,
"created":1603237484000,
"modified":"null",
"status":"Shipment Completed",
"amount":1000.0}
]