#%RAML 1.0 NamedExample
[
{"productid":0,
"categoryid":10,
"name":"FZA",
"description":"NEHA",
"video_url":"www.craft.com",
"price":4414.0},

{"productid":1,
"categoryid":15,
"name":"DELL PC",
"description":"CORE I 7",
"video_url":"WWW.DELL.COM",
"price":2000.0},

{"productid":2,
"categoryid":18,
"name":"DELL PC",
"description":"CORE I 7",
"video_url":"WWW.DELL.COM",
"price":2000.0},

{"productid":3,
"categoryid":20,
"name":"ACER PC",
"description":"CORE I 7",
"video_url":"WWW.ACER.COM",
"price":500.0},

{"productid":4,
"categoryid":18,
"name":"HP PC",
"description":"CORE I 7",
"video_url":"WWW.HP.COM",
"price":350.0},

{"productid":5,
"categoryid":16,
"name":"LENOVO PC",
"description":"CORE I 5",
"video_url":"WWW.LENOVO.COM",
"price":1200.0},

{"productid":6,
"categoryid":15,
"name":"DELL PC",
"description":"CORE I 5",
"video_url":"WWW.DELL.COM",
"price":700.0}
]
