#%RAML 1.0 NamedExample
[
{"userid":1812,
"email":"solomon.a@gmail.com",
"date_joined":1605207641000,
"modified":1605207641000,
"type":1,
"deleted":false,
"username":"Jose_Morinio"},

{"userid":1813,
"email":"biresh.a@gmail.com",
"date_joined":1605207729000,
"modified":1605207729000,
"type":1,
"deleted":false,
"username":"adane_girma"},

{"userid":1814,
"email":"sewmone.d@gmail.com",
"date_joined":1605208116000,
"modified":1605208116000,
"type":1,
"deleted":false,
"username":"Dedior_Drogba"},

{"userid":1815,
"email":"ambasel.d@gmail.com",
"date_joined":1605209316000,
"modified":1605209316000,
"type":1,
"deleted":false,
"username":"kezira"},

{"userid":1816,
"email":"tirukene.w@gmail.com",
"date_joined":1605209566000,
"modified":1605209566000,
"type":1,
"deleted":false,
"username":"bilen"},

{"userid":1817,
"email":"doitnow_t@gmail.com",
"date_joined":1605209723000,
"modified":1605209723000,
"type":1,
"deleted":false,
"username":"doitnow"},

{"userid":1818,
"email":"Desta.b@corena.com",
"date_joined":1605218653000,
"modified":1605218653000,
"type":1,
"deleted":false,
"username":"corenayitfa"},

{"userid":1846,
"email":"zer@gmail.com",
"date_joined":1605580310000,
"modified":1605580310000,
"type":1,
"deleted":false,
"username":"zer"}
]