#%RAML 1.0 ResourceType
get:
    description: Get the list of all the categories currently in the system
    responses:
      200:
        body:
          application/json:
            type: categoryDatatype []
            example: !include ../Examples/categories.raml