#%RAML 1.0 Library
usage: all list of library
types:
  userdatatype: !include datatypes/user.raml
  orderDataType: !include datatypes/order.raml
  catagoriesDataType: !include datatypes/catagories.raml
  productDataTypes: !include datatypes/product.raml
  productIDDataTypes: !include datatypes/productIDdataType.raml
  POSTorder_DataTypes: !include datatypes/dataTypePOST_order.raml

traits:
    traites: !include trait/trait.raml
    trait1: !include trait/ADMIN_trait.raml
securitySchemes:
  securty: !include securityScheme.raml
resourceTypes:
  CatagoryResourceType: !include resource/Catagory_ResourceType.raml
  ProductResourceType: !include resource/Product_resourceType.raml
  UserResourceType: !include resource/User_resourceType.raml
  OrderResourceType: !include resource/order_ResourceType.raml 
  
  
  

 