#%RAML 1.0 Overlay
extends: craft_online_shoping.raml
title: online shopping overview
documentation:
  - title: overview
    content: the documents define about online shopping
    /product:
usage: 
      - to provide the extra langouge determination with spanish  
description: updating with spanish language