#%RAML 1.0 DocumentationItem
title: Craft online shopping API
content:
  Welcome to craft online shopping API documentation. Craft online shopping API allows you to connect your application to our online craft shopping. 

    This API contains resources:- 
      1 products
      2.users
      3.orders
      4.categories
  
  Each resource has its own http methods. In addition data type, resource type, traits, library, overlay and security schema were defined. 
  Besides administration support, operation resources and http methods are included in the extension part of the API.  

  





  
  
