#%RAML 1.0 Overlay
extends: craft-online-shopping-gr-b.raml
title: Craft online shopping overview
documentation:
  - title: overview
    content: the document define about the online shopping product 
    /product:
usage:
 To provide additional information about the rest api for Spanish as well as French speakers.

  

  