#%RAML 1.0 NamedExample
[
    {
        "orderid": 1503,
        "userid": 1001,
        "addressid": 201,
        "discountid": 1,
        "created": 1603214000000,
        "modified": null,
        "status": "Shipment Completed",
        "amount": 1000.0
    },
    {
        "orderid": 1504,
        "userid": 1005,
        "addressid": 201,
        "discountid": 1,
        "created": 1603214084000,
        "modified": null,
        "status": "Shipment Completed",
        "amount": 1000.0
    }]