#%RAML 1.0 ResourceType
get:
    description: <<resourcePathName>> 
    responses:
      200:
        body:
          application/json:
             example: get all <<resourcePath>>
             
               
            