#%RAML 1.0 ResourceType
get:
  description: 
  responses:
    200:
      description: 
      body:
        application/json:
          type: lib.productDataTypes[]
          example: !include ../example/product.raml
          