#%RAML 1.0 ResourceType
get:
    description:  
    responses:
      200:
        body:
          application/json:
            type: lib.userdatatype[]
            example: !include ../example/user.raml
               