#%RAML 1.0 Trait
 responses:
    
    404:
        description: data not found
        body:
          application/json:
            example:
              {
                massage: "error data not found"
              } 
    401:
        description:  unauthorized user
        body:
          application/json:
            example:
              {
                massage: "unauthorized user"
              }           
    500:
      description: server failed 
      body:
        application/json:
          example:
            {
              massage: "server failed"
            } 